<a href="https://colab.research.google.com/github/kumoromilee/BasicProg_DataViz65/blob/main/Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Slicing

In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [ ]:
mat_b[-5:,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
mat_a[1:2]

array([[1, 2, 3]])

In [ ]:
mat_b[1:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])